### ISSUE TITLE
Package versions?

### ISSUE THREAD

**Issue by gitUser128954** [U54Bioinformatics/PhylinSic_Project#2]
I know you had rJava and picard/gatk4 issues, but can you provide the package version numbers for the working conda environment?

**Comment by jefftc** [comment]
Below is a list of the packages installed in my conda environment.

As you noted, I had issues with some of the libraries in conda (rJava, gatk4).  I worked around it by installing those packages separately, and ran the non-conda versions by configuring the following variables in the Snakefile: 
GATK
RSCRIPT
JAVA
BEAST2_DIR
LOGCOMBINER

Good luck!  I wish the installation were easier.  Hopefully, the issues will eventually resolve themselves when the conda packages are updated, or someone who is better at conda than me has a better solution.

Jeff




# packages in environment at /home/jchang4/mambaforge/envs/snakemake:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
aioeasywebdav             2.4.0              pyha770c72_0    conda-forge
aiohttp                   3.8.5           py311h459d7ec_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.9                hd590300_0    conda-forge
amply                     0.1.6              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astroid                   2.15.5                   pypi_0    pypi
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attmap                    0.13.2             pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2           py311hd4cff14_1    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
bioconductor-ggtree       3.6.0             r42hdfd78af_0    bioconda
bioconductor-treeio       1.22.0            r42hdfd78af_0    bioconda
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boto3                     1.28.9             pyhd8ed1ab_0    conda-forge
botocore                  1.31.9             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h409f033_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.10              h9002f0b_0    conda-forge
coin-or-cgl               0.60.7               h516709c_0    conda-forge
coin-or-clp               1.17.8               h1ee7a9c_0    conda-forge
coin-or-osi               0.108.8              ha2443b9_0    conda-forge
coin-or-utils             2.11.9               hee58242_0    conda-forge
coincbc                   2.10.10           0_metapackage    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.3.1          py311h38be061_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.8.0              pyhd8ed1ab_0    conda-forge
configargparse            1.5.5              pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
cryptography              41.0.2          py311h63ff55d_0    conda-forge
curl                      8.2.0                hca28451_0    conda-forge
datrie                    0.8.2           py311hd4cff14_6    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.6                    pypi_0    pypi
docutils                  0.20.1          py311h38be061_0    conda-forge
dpath                     2.1.6              pyha770c72_0    conda-forge
dropbox                   11.36.2            pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
filechunkio               1.8                        py_2    conda-forge
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozenlist                1.4.0           py311h459d7ec_0    conda-forge
ftputil                   5.0.4              pyhd8ed1ab_0    conda-forge
gcc_impl_linux-64         13.1.0               hc4be1a9_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    13.1.0               hd511a9b_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.32             pyhd8ed1ab_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
google-api-core           2.11.1             pyhd8ed1ab_0    conda-forge
google-api-python-client  2.94.0             pyhd8ed1ab_0    conda-forge
google-auth               2.22.0             pyh1a96a4e_0    conda-forge
google-auth-httplib2      0.1.0              pyhd8ed1ab_1    conda-forge
google-cloud-core         2.3.3              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.10.0             pyh1a96a4e_0    conda-forge
google-crc32c             1.1.2           py311h98db957_4    conda-forge
google-resumable-media    2.5.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.59.1             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpcio                    1.56.2          py311ha6695c7_0    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gxx_impl_linux-64         13.1.0               hc4be1a9_0    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
htslib                    1.17                 h81da01d_2    bioconda
httplib2                  0.22.0             pyhd8ed1ab_0    conda-forge
humanfriendly             10.0            py311h38be061_4    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib_resources       6.0.0              pyhd8ed1ab_1    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
isort                     5.12.0                   pypi_0    pypi
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.18.4             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1           py311h38be061_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.1               h659d440_0    conda-forge
lazy-object-proxy         1.9.0                    pypi_0    pypi
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.2.0                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     13.1.0               he3cc6c4_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgit2                   1.6.4                h747ad27_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgrpc                   1.56.2               h3905398_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
liblapacke                3.9.0           17_linux64_openblas    conda-forge
libmamba                  1.4.9                h658169a_0    conda-forge
libmambapy                1.4.9           py311h527f279_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.23.3               hd1fb520_0    conda-forge
libsanitizer              13.1.0               hfd8a6a1_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.24               hfc55251_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  13.1.0               he3cc6c4_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
logmuse                   0.2.6              pyh8c360ce_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
mamba                     1.4.9           py311h3072747_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
multidict                 6.0.4           py311h2582759_0    conda-forge
nbformat                  5.9.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     1.25.0          py311h64a7726_0    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
openjdk                   20.0.0               h8e330f5_0    conda-forge
openssl                   3.1.1                hd590300_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py311h320fe9a_1    conda-forge
pandoc                    2.19.2               h32600fe_2    conda-forge
pango                     1.50.14              heaa33ce_1    conda-forge
paramiko                  3.2.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
peppy                     0.35.7             pyhd8ed1ab_0    conda-forge
picard                    3.0.0                hdfd78af_0    bioconda
pip                       23.2               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
plac                      1.3.5              pyhd8ed1ab_0    conda-forge
platformdirs              3.9.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prettytable               3.8.0              pyhd8ed1ab_0    conda-forge
protobuf                  4.23.3          py311hbec7ed6_0    conda-forge
psutil                    5.9.5           py311h2582759_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulp                      2.7.0           py311h38be061_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py311hd4cff14_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pylint                    2.17.4                   pypi_0    pypi
pynacl                    1.5.0           py311hd4cff14_2    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.0              pyhd8ed1ab_0    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
python-irodsclient        1.1.8              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py311hd4cff14_5    conda-forge
r-ape                     5.7_1             r42h08d816e_1    conda-forge
r-aplot                   0.1.10            r42hc72bb7e_1    conda-forge
r-askpass                 1.1               r42h57805ef_4    conda-forge
r-assertthat              0.2.1             r42hc72bb7e_4    conda-forge
r-backports               1.4.1             r42h57805ef_2    conda-forge
r-base                    4.2.3                hb1b9b86_6    conda-forge
r-base64enc               0.1_3           r42h57805ef_1006    conda-forge
r-bit                     4.0.5             r42h57805ef_1    conda-forge
r-bit64                   4.0.5             r42h57805ef_2    conda-forge
r-brew                    1.0_8             r42hc72bb7e_2    conda-forge
r-brio                    1.1.3             r42h57805ef_2    conda-forge
r-bslib                   0.5.0             r42hc72bb7e_1    conda-forge
r-cachem                  1.0.8             r42h57805ef_1    conda-forge
r-callr                   3.7.3             r42hc72bb7e_1    conda-forge
r-cli                     3.6.1             r42ha503ecb_1    conda-forge
r-clipr                   0.8.0             r42hc72bb7e_2    conda-forge
r-colorspace              2.1_0             r42h57805ef_1    conda-forge
r-commonmark              1.9.0             r42h57805ef_1    conda-forge
r-cpp11                   0.4.5             r42hc72bb7e_0    conda-forge
r-crayon                  1.5.2             r42hc72bb7e_2    conda-forge
r-credentials             1.3.2             r42hc72bb7e_2    conda-forge
r-curl                    5.0.1             r42hf9611b0_0    conda-forge
r-data.table              1.14.8            r42h029312a_2    conda-forge
r-desc                    1.4.2             r42hc72bb7e_2    conda-forge
r-devtools                2.4.5             r42hc72bb7e_2    conda-forge
r-diffobj                 0.3.5             r42h57805ef_2    conda-forge
r-digest                  0.6.33            r42ha503ecb_0    conda-forge
r-downlit                 0.4.3             r42hc72bb7e_0    conda-forge
r-dplyr                   1.1.2             r42ha503ecb_1    conda-forge
r-ellipsis                0.3.2             r42h57805ef_2    conda-forge
r-evaluate                0.21              r42hc72bb7e_1    conda-forge
r-fansi                   1.0.4             r42h57805ef_1    conda-forge
r-farver                  2.1.1             r42ha503ecb_2    conda-forge
r-fastmap                 1.1.1             r42ha503ecb_1    conda-forge
r-fastmatch               1.1_3             r42h57805ef_2    conda-forge
r-fontawesome             0.5.1             r42hc72bb7e_1    conda-forge
r-fs                      1.6.3             r42ha503ecb_0    conda-forge
r-gbrd                    0.4_11          r42hc72bb7e_1005    conda-forge
r-generics                0.1.3             r42hc72bb7e_2    conda-forge
r-gert                    1.9.2             r42h1ab2d24_2    conda-forge
r-ggfun                   0.1.1             r42hc72bb7e_0    conda-forge
r-ggplot2                 3.4.2             r42hc72bb7e_1    conda-forge
r-ggplotify               0.1.1             r42hc72bb7e_0    conda-forge
r-gh                      1.4.0             r42hc72bb7e_1    conda-forge
r-gitcreds                0.1.2             r42hc72bb7e_2    conda-forge
r-glue                    1.6.2             r42h57805ef_2    conda-forge
r-gridgraphics            0.5_1             r42hc72bb7e_2    conda-forge
r-gtable                  0.3.3             r42hc72bb7e_1    conda-forge
r-highr                   0.10              r42hc72bb7e_1    conda-forge
r-htmltools               0.5.5             r42ha503ecb_1    conda-forge
r-htmlwidgets             1.6.2             r42hc72bb7e_1    conda-forge
r-httpuv                  1.6.11            r42ha503ecb_1    conda-forge
r-httr                    1.4.6             r42hc72bb7e_1    conda-forge
r-httr2                   0.2.3             r42hc72bb7e_1    conda-forge
r-igraph                  1.4.3             r42h9254619_1    conda-forge
r-ini                     0.3.1           r42hc72bb7e_1005    conda-forge
r-isoband                 0.2.7             r42ha503ecb_2    conda-forge
r-jquerylib               0.1.4             r42hc72bb7e_2    conda-forge
r-jsonlite                1.8.7             r42h57805ef_0    conda-forge
r-knitr                   1.43              r42hc72bb7e_1    conda-forge
r-labeling                0.4.2             r42hc72bb7e_3    conda-forge
r-later                   1.3.1             r42ha503ecb_1    conda-forge
r-lattice                 0.21_8            r42h57805ef_1    conda-forge
r-lazyeval                0.2.2             r42h57805ef_4    conda-forge
r-lifecycle               1.0.3             r42hc72bb7e_2    conda-forge
r-magrittr                2.0.3             r42h57805ef_2    conda-forge
r-mass                    7.3_60            r42h57805ef_1    conda-forge
r-matrix                  1.6_0             r42h316c678_0    conda-forge
r-memoise                 2.0.1             r42hc72bb7e_2    conda-forge
r-mgcv                    1.9_0             r42h316c678_0    conda-forge
r-mime                    0.12              r42h57805ef_2    conda-forge
r-miniui                  0.1.1.1         r42hc72bb7e_1004    conda-forge
r-munsell                 0.5.0           r42hc72bb7e_1006    conda-forge
r-nlme                    3.1_162           r42h61816a4_1    conda-forge
r-openssl                 2.0.6             r42hb353fa6_1    conda-forge
r-patchwork               1.1.2             r42hc72bb7e_2    conda-forge
r-phangorn                2.11.1            r42h7ce84a7_1    conda-forge
r-pillar                  1.9.0             r42hc72bb7e_1    conda-forge
r-pkgbuild                1.4.2             r42hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r42hc72bb7e_3    conda-forge
r-pkgdown                 2.0.7             r42hc72bb7e_1    conda-forge
r-pkgload                 1.3.2.1           r42hc72bb7e_0    conda-forge
r-plottools               0.2.0             r42hc72bb7e_1    conda-forge
r-praise                  1.0.0           r42hc72bb7e_1007    conda-forge
r-prettyunits             1.1.1             r42hc72bb7e_3    conda-forge
r-processx                3.8.2             r42h57805ef_0    conda-forge
r-profvis                 0.3.8             r42h57805ef_2    conda-forge
r-promises                1.2.0.1           r42ha503ecb_2    conda-forge
r-ps                      1.7.5             r42h57805ef_1    conda-forge
r-purrr                   1.0.1             r42h57805ef_1    conda-forge
r-quadprog                1.5_8             r42h13b3f57_5    conda-forge
r-r.cache                 0.16.0            r42hc72bb7e_2    conda-forge
r-r.methodss3             1.8.2             r42hc72bb7e_2    conda-forge
r-r.oo                    1.25.0            r42hc72bb7e_2    conda-forge
r-r.utils                 2.12.2            r42hc72bb7e_1    conda-forge
r-r6                      2.5.1             r42hc72bb7e_2    conda-forge
r-ragg                    1.2.5             r42h85cdef0_2    conda-forge
r-rappdirs                0.3.3             r42h57805ef_2    conda-forge
r-rbibutils               2.2.13            r42h57805ef_1    conda-forge
r-rcmdcheck               1.4.0             r42h785f33e_2    conda-forge
r-rcolorbrewer            1.1_3             r42h785f33e_2    conda-forge
r-rcpp                    1.0.11            r42h7df8631_0    conda-forge
r-rdpack                  2.4               r42hc72bb7e_2    conda-forge
r-rematch2                2.1.2             r42hc72bb7e_3    conda-forge
r-remotes                 2.4.2.1           r42hc72bb7e_0    conda-forge
r-rlang                   1.1.1             r42ha503ecb_1    conda-forge
r-rmarkdown               2.23              r42hc72bb7e_0    conda-forge
r-roxygen2                7.2.3             r42ha503ecb_1    conda-forge
r-rprojroot               2.0.3             r42hc72bb7e_1    conda-forge
r-rstudioapi              0.15.0            r42hc72bb7e_0    conda-forge
r-rversions               2.1.2             r42hc72bb7e_2    conda-forge
r-sass                    0.4.7             r42ha503ecb_0    conda-forge
r-scales                  1.2.1             r42hc72bb7e_2    conda-forge
r-sessioninfo             1.2.2             r42hc72bb7e_2    conda-forge
r-shiny                   1.7.4.1           r42h785f33e_0    conda-forge
r-sourcetools             0.1.7_1           r42ha503ecb_1    conda-forge
r-stringi                 1.7.12            r42hc0c3e09_2    conda-forge
r-stringr                 1.5.0             r42h785f33e_1    conda-forge
r-sys                     3.4.2             r42h57805ef_1    conda-forge
r-systemfonts             1.0.4             r42haf97adc_2    conda-forge
r-testthat                3.1.10            r42ha503ecb_0    conda-forge
r-textshaping             0.3.6             r42h24cd192_6    conda-forge
r-tibble                  3.2.1             r42h57805ef_2    conda-forge
r-tidyr                   1.3.0             r42ha503ecb_1    conda-forge
r-tidyselect              1.2.0             r42hc72bb7e_1    conda-forge
r-tidytree                0.4.4             r42hc72bb7e_0    conda-forge
r-tinytex                 0.45              r42hc72bb7e_1    conda-forge
r-treetools               1.9.2             r42ha503ecb_1    conda-forge
r-urlchecker              1.0.1             r42hc72bb7e_2    conda-forge
r-usethis                 2.2.2             r42hc72bb7e_0    conda-forge
r-utf8                    1.2.3             r42h57805ef_1    conda-forge
r-vctrs                   0.6.3             r42ha503ecb_0    conda-forge
r-viridislite             0.4.2             r42hc72bb7e_1    conda-forge
r-waldo                   0.5.1             r42hc72bb7e_1    conda-forge
r-whisker                 0.4.1             r42hc72bb7e_1    conda-forge
r-withr                   2.5.0             r42hc72bb7e_2    conda-forge
r-xfun                    0.39              r42ha503ecb_1    conda-forge
r-xml2                    1.3.5             r42h1ad5fc0_0    conda-forge
r-xopen                   1.0.0           r42hc72bb7e_1005    conda-forge
r-xtable                  1.8_4             r42hc72bb7e_5    conda-forge
r-yaml                    2.3.7             r42h57805ef_1    conda-forge
r-yulab.utils             0.0.6             r42hc72bb7e_1    conda-forge
r-zip                     2.3.0             r42h57805ef_1    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.30.0             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
reretry                   0.11.8             pyhd8ed1ab_0    conda-forge
rich                      13.4.2             pyhd8ed1ab_0    conda-forge
rpds-py                   0.9.2           py311h46250e7_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.32         py311h459d7ec_0    conda-forge
ruamel.yaml.clib          0.2.7           py311h2582759_1    conda-forge
s3transfer                0.6.1              pyhd8ed1ab_0    conda-forge
samtools                  1.17                 hd87286a_1    bioconda
scipy                     1.10.1          py311h64a7726_3    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            7.1.0              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slacker                   0.14.0                     py_0    conda-forge
smart_open                6.3.0              pyhd8ed1ab_1    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakemake                 7.26.0               hdfd78af_0    bioconda
snakemake-minimal         7.26.0             pyhdfd78af_0    bioconda
stone                     3.3.1              pyhd8ed1ab_0    conda-forge
stopit                    1.1.2                      py_0    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
throttler                 1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.8                   pypi_0    pypi
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ubiquerg                  0.6.2              pyhd8ed1ab_0    conda-forge
uritemplate               4.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
varscan                   2.4.4                hdfd78af_1    bioconda
veracitools               0.1.3                      py_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.15.0          py311h2582759_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_0    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
yarl                      1.9.2           py311h459d7ec_0    conda-forge
yte                       1.5.1              pyha770c72_2    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0          py311haa97af0_2    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge

**Comment by gitUser128954** [comment]
Thank you! I hope it works without an issue too, but just in case.
